services:
  cloud-function:
    build: .
    command: npm run dev
    ports:
      - '8090:8090'
    networks:
      - breedersdb_net
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: rebuild
          path: .env
        - action: rebuild
          path: Dockerfile
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
            - README.md

networks:
  breedersdb_net:
    name: breedersdb_net
