project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /src/i18n/en-US/*.ts
    translation: /src/i18n/%locale%/%original_file_name%
    ignore:
      - /src/i18n/**/index.ts
