
#base_path: "/"
#base_url: "https://api.crowdin.com"

files:
  - source: /resources/locales/*.pot
    translation: /resources/locales/%two_letters_code%/%file_name%.po
  - source: /webroot/v2/src/i18n/en-US/*.ts
    translation: /webroot/v2/src/i18n/%two_letters_code%/%original_file_name%
