export const plantGroups = {
  title: 'Group | Groups',

  fields: {
    labelId: 'Label ID',
    cultivar: 'Cultivar',
  },

  searchPlaceholderName: 'Search by name or label ID',

  disableConfirmation:
    'Disabling will make it impossible to add plants to this group. Do you really want to disable it?',
  deleteConfirmation:
    "This group doesn't have any plants and will therefore be permanently deleted. Are you sure?",

  labelIdHint: 'Automatically generated by the database. Cannot be changed.',
};
