@startuml
title Database Schema
hide circle
skinparam linetype ortho

entity "**analyze_filter_base_tables**" {
  + ""enum"": //text [PK]//
  --
}

entity "**analyze_filters**" {
  + ""id"": //integer [PK]//
  --
  *""name"": //citext //
  ""note"": //character varying(2047) //
  *""base_table"": //text [FK]//
  ""base_filter"": //jsonb //
  ""attribution_filter"": //jsonb //
  *""visible_columns"": //text[] //
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

entity "**attribute_data_types**" #00ff0012 ##008800 {
  + ""enum"": //text [PK]//
  --
}

entity "**attribute_types**" #00ff0012 ##008800 {
  + ""enum"": //text [PK]//
  --
}

entity "**attributes**" #00ff0012 ##008800 {
  ""- validation_rule"":\n""    JSONB: {min: int, max: int, step: int}"" for ""INTEGER"",\n""           {min: int &gt;= 0, max: int &lt;= 9, step: 1}"" for ""RATING""\n""           {min: float|int, max: float|int, step: float|int}"" for ""FLOAT""\n""    NULL"" for other data types.\n""- data_type"": Can&#39;t be changed once ""attribution_values"" for this ""attribute"" exist.\n""- legend"": Only supported for data_type RATING\n""- default_value"": Not supported for data_type PHOTO\n
  ..
  + ""id"": //integer [PK]//
  --
  *""name"": //citext //
  ""validation_rule"": //jsonb //
  ""default_value"": //jsonb //
  *""data_type"": //text [FK]//
  ""description"": //character varying(255) //
  ""legend"": //jsonb //
  *""attribute_type"": //text [FK]//
  *""disabled"": //boolean //
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

entity "**attribution_form_fields**" #00ff0012 ##008800 {
  + ""id"": //integer [PK]//
  --
  *""priority"": //integer //
  *""attribution_form_id"": //integer [FK]//
  *""attribute_id"": //integer [FK]//
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
  *""required"": //boolean //
}

entity "**attribution_forms**" #00ff0012 ##008800 {
  + ""id"": //integer [PK]//
  --
  *""name"": //citext //
  ""description"": //character varying(255) //
  *""disabled"": //boolean //
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

entity "**attribution_values**" #00ff0012 ##008800 {
  ""- text_value"" is trimmed.\n""- integer_value"" and ""float_value"" are checked against the\n""  ""corresponding ""attribute.validation_rule"".\n""  ""The checking is performed on insert and update of the value\n""  ""but not revalidated if the ""validation_rule"" changes.
  ..
  + ""id"": //integer [PK]//
  --
  *""attribute_id"": //integer [FK]//
  *""attribution_id"": //integer [FK]//
  ""integer_value"": //integer //
  ""float_value"": //double precision //
  ""text_value"": //citext //
  ""boolean_value"": //boolean //
  ""date_value"": //date //
  ""text_note"": //character varying(2047) //
  ""photo_note"": //character varying(69) //
  *""exceptional_attribution"": //boolean //
  ""offline_id"": //uuid //
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

entity "**attributions**" #00ff0012 ##008800 {
  + ""id"": //integer [PK]//
  --
  *""author"": //citext //
  *""date_attributed"": //date //
  *""attribution_form_id"": //integer [FK]//
  ""plant_id"": //integer [FK]//
  ""plant_group_id"": //integer [FK]//
  ""cultivar_id"": //integer [FK]//
  ""lot_id"": //integer [FK]//
  ""geo_location"": //geography(Point,4326)  : SRID:4326//
  ""geo_location_accuracy"": //double precision  : Meters//
  ""offline_id"": //uuid //
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

entity "**cached_attributions**" {
  Incrementally updated view for attributions.\nMaintained by triggers. Do not update manually. Read only.
  ..
  + ""id"": //integer [PK]//
  --
  ""integer_value"": //integer //
  ""float_value"": //double precision //
  ""text_value"": //citext //
  ""boolean_value"": //boolean //
  ""date_value"": //date //
  ""text_note"": //character varying(2047) //
  ""photo_note"": //character varying(69) //
  *""exceptional_attribution"": //boolean //
  *""attribute_name"": //citext //
  *""attribute_id"": //integer [FK]//
  *""data_type"": //text [FK]//
  *""attribute_type"": //text [FK]//
  *""attribution_id"": //integer [FK]//
  ""plant_id"": //integer [FK]//
  ""plant_group_id"": //integer [FK]//
  ""cultivar_id"": //integer [FK]//
  ""lot_id"": //integer [FK]//
  *""attribution_form_id"": //integer [FK]//
  ""combined_plant_group_id"": //integer [FK]//
  ""combined_cultivar_id"": //integer [FK]//
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
  *""author"": //citext //
  *""date_attributed"": //date //
  ""geo_location"": //geography(Point,4326) //
  ""geo_location_accuracy"": //double precision //
}

entity "**crossings**" #ffff0012 ##888800 {
  + ""id"": //integer [PK]//
  --
  *""name"": //citext //
  ""mother_cultivar_id"": //integer [FK]//
  ""father_cultivar_id"": //integer [FK]//
  *""is_variety"": //boolean //
  ""note"": //character varying(2047) //
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

entity "**cultivars**" #ffff0012 ##888800 {
  + ""id"": //integer [PK]//
  --
  *""lot_id"": //integer [FK]//
  *""is_variety"": //boolean  : Set by triggers.//
  *""name_segment"": //citext //
  *""full_name"": //citext  : Set by triggers.//
  ""name_override"": //citext //
  *""display_name"": //citext  : Generated.//
  ""acronym"": //citext //
  ""breeder"": //character varying(255) //
  ""note"": //character varying(2047) //
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

entity "**graftings**" #0000ff12 ##000088 {
  + ""id"": //integer [PK]//
  --
  *""name"": //citext //
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

entity "**logged_actions**" {
  + ""id"": //integer [PK]//
  --
  *""name"": //text //
  *""subject"": //text //
  ""context"": //jsonb //
  *""created"": //timestamp with time zone //
}

entity "**lots**" #ffff0012 ##888800 {
  + ""id"": //integer [PK]//
  --
  *""crossing_id"": //integer [FK]//
  *""is_variety"": //boolean  : Set by triggers.//
  *""name_segment"": //citext //
  *""full_name"": //citext  : Set by triggers.//
  ""name_override"": //citext //
  *""display_name"": //citext  : Generated.//
  ""date_sowed"": //date //
  ""numb_seeds_sowed"": //integer //
  ""numb_seedlings_grown"": //integer //
  ""seed_tray"": //character varying(255) //
  ""date_planted"": //date //
  ""numb_seedlings_planted"": //integer //
  ""plot"": //character varying(255) //
  *""orchard_id"": //integer [FK]//
  ""note"": //character varying(2047) //
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

entity "**mother_plants**" #0000ff06 {
  + ""id"": //integer [PK]//
  --
  *""name"": //citext //
  ""date_impregnated"": //date //
  ""date_fruits_harvested"": //date //
  ""numb_flowers"": //integer //
  ""numb_fruits"": //integer //
  ""numb_seeds"": //integer //
  ""note"": //character varying(2047) //
  *""plant_id"": //integer [FK]//
  ""pollen_id"": //integer [FK]//
  *""crossing_id"": //integer [FK]//
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

entity "**orchards**" #0000ff12 ##000088 {
  + ""id"": //integer [PK]//
  --
  *""name"": //citext //
  *""disabled"": //boolean //
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

entity "**plant_groups**" #ffff0012 ##888800 {
  + ""id"": //integer [PK]//
  --
  ""label_id"": //citext  : Generated.//
  *""cultivar_id"": //integer [FK]//
  *""cultivar_name"": //citext  : Set by triggers.//
  *""name_segment"": //citext //
  ""full_name"": //citext  : Generated.//
  ""name_override"": //citext //
  *""display_name"": //citext  : Generated.//
  ""note"": //character varying(2047) //
  *""disabled"": //boolean //
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

entity "**plant_rows**" #0000ff12 ##000088 {
  + ""id"": //integer [PK]//
  --
  *""name"": //citext //
  *""orchard_id"": //integer [FK]//
  ""note"": //character varying(2047) //
  ""date_created"": //date //
  ""date_eliminated"": //date //
  *""disabled"": //boolean  : Derived from date_eliminated.//
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

entity "**plants**" #0000ff12 ##000088 {
  + ""id"": //integer [PK]//
  --
  *""label_id"": //citext //
  *""plant_group_id"": //integer [FK]//
  *""plant_group_name"": //citext  : Set by triggers.//
  *""cultivar_name"": //citext  : Set by triggers.//
  ""plant_row_id"": //integer [FK]//
  ""serial_in_plant_row"": //integer //
  ""distance_plant_row_start"": //double precision  : Meters//
  ""geo_location"": //geography(Point,4326)  : SRID:4326//
  ""geo_location_accuracy"": //double precision  : Meters//
  ""date_grafted"": //date //
  ""date_planted"": //date //
  ""date_eliminated"": //date //
  ""date_labeled"": //date //
  ""note"": //character varying(2047) //
  ""rootstock_id"": //integer [FK]//
  ""grafting_id"": //integer [FK]//
  *""disabled"": //boolean  : Derived from date_eliminated.//
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

entity "**pollen**" #0000ff06 {
  + ""id"": //integer [PK]//
  --
  *""name"": //citext //
  ""date_harvested"": //date //
  ""note"": //character varying(2047) //
  *""cultivar_id"": //integer [FK]//
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

entity "**rootstocks**" #0000ff12 ##000088 {
  + ""id"": //integer [PK]//
  --
  *""name"": //citext //
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

entity "**user_tokens**" {
  + ""id"": //integer [PK]//
  --
  *""user_id"": //integer [FK]//
  *""token_hash"": //character varying(64) //
  *""type"": //character varying(10) //
  *""created"": //timestamp with time zone //
  ""last_verify"": //timestamp with time zone //
}

entity "**users**" {
  + ""id"": //integer [PK]//
  --
  *""email"": //citext //
  *""password_hash"": //character varying(128) //
  *""locale"": //character varying(5) //
  ""last_signin"": //timestamp with time zone  : Successful signin.//
  *""failed_signin_attempts"": //integer  : Failed attempts only. Reset on successful signin.//
  ""first_failed_signin_attempt"": //timestamp with time zone //
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
}

"**analyze_filters**"   }--  "**analyze_filter_base_tables**"

"**attributes**"   }--  "**attribute_types**"

"**attributes**"   }--  "**attribute_data_types**"

"**attribution_form_fields**"   }--  "**attributes**"

"**attribution_form_fields**"   }--  "**attribution_forms**"

"**attribution_values**"   }--  "**attributes**"

"**attribution_values**"   }--  "**attributions**"

"**attributions**"   }--  "**attribution_forms**"

"**attributions**"   }--  "**cultivars**"

"**attributions**"   }--  "**lots**"

"**attributions**"   }--  "**plant_groups**"

"**attributions**"   }--  "**plants**"

"**cached_attributions**"   }--  "**attributes**"

"**cached_attributions**"   }--  "**attribute_types**"

"**cached_attributions**"   }--  "**attribution_forms**"

"**cached_attributions**"   }--  "**attributions**"

"**cached_attributions**"   }--  "**cultivars**"

"**cached_attributions**"   }--  "**plant_groups**"

"**cached_attributions**"   }--  "**cultivars**"

"**cached_attributions**"   }--  "**attribute_data_types**"

"**cached_attributions**"   }--  "**lots**"

"**cached_attributions**"   }--  "**plant_groups**"

"**cached_attributions**"   }--  "**plants**"

"**crossings**"   }--  "**cultivars**"

"**crossings**"   }--  "**cultivars**"

"**cultivars**"   }--  "**lots**"

"**lots**"   }--  "**crossings**"

"**lots**"   }--  "**orchards**"

"**mother_plants**"   }--  "**crossings**"

"**mother_plants**"   }--  "**plants**"

"**mother_plants**"   }--  "**pollen**"

"**plant_groups**"   }--  "**cultivars**"

"**plant_rows**"   }--  "**orchards**"

"**plants**"   }--  "**graftings**"

"**plants**"   }--  "**plant_groups**"

"**plants**"   }--  "**plant_rows**"

"**plants**"   }--  "**rootstocks**"

"**pollen**"   }--  "**cultivars**"

"**user_tokens**"   }--  "**users**"
@enduml
