@startuml
title Database Schema
hide circle
skinparam linetype ortho

entity "**attribute_data_types**" #00ff0012 ##008800 {
  + ""enum"": //text [PK]//
  --
}

entity "**attribute_types**" #00ff0012 ##008800 {
  + ""enum"": //text [PK]//
  --
}

entity "**attribute_values**" #00ff0012 ##008800 {
  ""- text_value"" is trimmed.\n""- integer_value"" and ""float_value"" are checked against the\n""  ""corresponding ""attribute.validation_rule"".\n""  ""The checking is performed on insert and update of the value\n""  ""but not revalidated if the ""validation_rule"" changes.
  ..
  + ""id"": //integer [PK]//
  --
  *""attribute_id"": //integer [FK]//
  *""attribution_id"": //integer [FK]//
  ""integer_value"": //integer //
  ""float_value"": //double precision //
  ""text_value"": //character varying(2047) //
  ""boolean_value"": //boolean //
  ""date_value"": //date //
  ""note"": //character varying(2047) //
  *""exceptional_attribution"": //boolean //
  ""offline_id"": //uuid //
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**attributes**" #00ff0012 ##008800 {
  ""- validation_rule"":\n""    JSONB: {min: int, max: int, step: int}"" for ""INTEGER"",\n""           {min: float|int, max: float|int, step: float|int}"" for ""FLOAT""\n""    NULL"" for other data types.\n""- data_type"": Can&#39;t be changed once ""attribute_values"" for this ""attribute"" exist.
  ..
  + ""id"": //integer [PK]//
  --
  *""name"": //character varying(45) //
  ""validation_rule"": //jsonb //
  *""data_type"": //character varying(12) [FK]//
  ""description"": //character varying(255) //
  *""attribute_type"": //character varying(12) [FK]//
  *""disabled"": //boolean //
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**attribution_form_fields**" #00ff0012 ##008800 {
  + ""id"": //integer [PK]//
  --
  *""priority"": //integer //
  *""attribution_form_id"": //integer [FK]//
  *""attribute_id"": //integer [FK]//
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**attribution_forms**" #00ff0012 ##008800 {
  + ""id"": //integer [PK]//
  --
  *""name"": //character varying(45) //
  ""description"": //character varying(255) //
  *""disabled"": //boolean //
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**attributions**" #00ff0012 ##008800 {
  + ""id"": //integer [PK]//
  --
  *""author"": //character varying(45) //
  *""date_attributed"": //date //
  *""attribution_form_id"": //integer [FK]//
  ""plant_id"": //integer [FK]//
  ""plant_group_id"": //integer [FK]//
  ""cultivar_id"": //integer [FK]//
  ""lot_id"": //integer [FK]//
  ""geo_location"": //geography(Point,4326)  : SRID:4326//
  ""geo_location_accuracy"": //double precision  : Meters//
  ""offline_id"": //uuid //
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**crossings**" #ffff0012 ##888800 {
  + ""id"": //integer [PK]//
  --
  *""name"": //character varying(8) //
  ""mother_cultivar_id"": //integer [FK]//
  ""father_cultivar_id"": //integer [FK]//
  ""note"": //character varying(2047) //
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**cultivars**" #ffff0012 ##888800 {
  + ""id"": //integer [PK]//
  --
  *""lot_id"": //integer [FK]//
  *""name_segment"": //character varying(25) //
  *""full_name"": //character varying(51)  : Set by triggers.//
  ""name_override"": //character varying(51) //
  ""display_name"": //character varying(51)  : Generated.//
  ""acronym"": //character varying(10) //
  ""breeder"": //character varying(255) //
  ""registration"": //character varying(255) //
  ""note"": //character varying(2047) //
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**graftings**" #0000ff12 ##000088 {
  + ""id"": //integer [PK]//
  --
  *""name"": //character varying(45) //
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**lots**" #ffff0012 ##888800 {
  + ""id"": //integer [PK]//
  --
  *""crossing_id"": //integer [FK]//
  *""name_segment"": //character varying(3) //
  *""full_name"": //character varying(12)  : Set by triggers.//
  ""name_override"": //character varying(25) //
  ""display_name"": //character varying(25)  : Generated.//
  ""date_sowed"": //date //
  ""numb_seeds_sowed"": //integer //
  ""numb_seedlings_grown"": //integer //
  ""seed_tray"": //character varying(255) //
  ""date_planted"": //date //
  ""numb_seedlings_planted"": //integer //
  ""plot"": //character varying(255) //
  *""orchard_id"": //integer [FK]//
  ""note"": //character varying(2047) //
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**materialized_view_refreshes**" {
  + ""id"": //integer [PK]//
  --
  *""view_name"": //character varying(63) //
  ""last_change"": //timestamp with time zone //
  ""last_check"": //timestamp with time zone //
}

entity "**mother_plants**" #0000ff06 {
  + ""id"": //integer [PK]//
  --
  *""name"": //character varying(45) //
  ""date_impregnated"": //date //
  ""date_fruits_harvested"": //date //
  ""numb_flowers"": //integer //
  ""numb_fruits"": //integer //
  ""numb_seeds"": //integer //
  ""note"": //character varying(2047) //
  *""plant_id"": //integer [FK]//
  ""pollen_id"": //integer [FK]//
  *""crossing_id"": //integer [FK]//
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**orchards**" #0000ff12 ##000088 {
  + ""id"": //integer [PK]//
  --
  *""name"": //character varying(45) //
  *""disabled"": //boolean //
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**plant_groups**" #ffff0012 ##888800 {
  + ""id"": //integer [PK]//
  --
  ""label_id"": //character varying(9)  : Generated.//
  *""cultivar_id"": //integer [FK]//
  *""cultivar_name"": //character varying(51)  : Set by triggers.//
  *""name_segment"": //character varying(25) //
  ""full_name"": //character varying(77)  : Generated.//
  ""name_override"": //character varying(77) //
  ""display_name"": //character varying(77)  : Generated.//
  ""note"": //character varying(2047) //
  *""disabled"": //boolean //
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**plant_rows**" #0000ff12 ##000088 {
  + ""id"": //integer [PK]//
  --
  *""name"": //character varying(45) //
  *""orchard_id"": //integer [FK]//
  ""note"": //character varying(2047) //
  ""date_created"": //date //
  ""date_eliminated"": //date //
  *""disabled"": //boolean  : Derived from date_eliminated.//
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**plants**" #0000ff12 ##000088 {
  + ""id"": //integer [PK]//
  --
  *""label_id"": //character varying(9) //
  *""plant_group_id"": //integer [FK]//
  *""plant_group_name"": //character varying(77)  : Set by triggers.//
  *""cultivar_name"": //character varying(51)  : Set by triggers.//
  ""plant_row_id"": //integer [FK]//
  ""serial_in_plant_row"": //integer //
  ""distance_plant_row_start"": //double precision  : Meters//
  ""geo_location"": //geography(Point,4326)  : SRID:4326//
  ""geo_location_accuracy"": //double precision  : Meters//
  ""date_grafted"": //date //
  ""date_planted"": //date //
  ""date_eliminated"": //date //
  ""date_labeled"": //date //
  ""note"": //character varying(2047) //
  ""rootstock_id"": //integer [FK]//
  ""grafting_id"": //integer [FK]//
  *""disabled"": //boolean  : Derived from date_eliminated.//
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**pollen**" #0000ff06 {
  + ""id"": //integer [PK]//
  --
  *""name"": //character varying(45) //
  ""date_harvested"": //date //
  ""note"": //character varying(2047) //
  *""cultivar_id"": //integer [FK]//
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**queries**" {
  + ""id"": //integer [PK]//
  --
  *""name"": //character varying(45) //
  *""my_query"": //jsonb //
  ""note"": //character varying(2047) //
  *""query_group_id"": //integer [FK]//
  ""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**query_groups**" {
  + ""id"": //integer [PK]//
  --
  *""name"": //character varying(45) //
  ""version"": //character varying(10) //
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

entity "**rootstocks**" #0000ff12 ##000088 {
  + ""id"": //integer [PK]//
  --
  *""name"": //character varying(45) //
  *""created"": //timestamp with time zone //
  ""modified"": //timestamp with time zone //
}

"**attribute_values**"   }--  "**attributes**"

"**attribute_values**"   }--  "**attributions**"

"**attributes**"   }--  "**attribute_types**"

"**attributes**"   }--  "**attribute_data_types**"

"**attribution_form_fields**"   }--  "**attributes**"

"**attribution_form_fields**"   }--  "**attribution_forms**"

"**attributions**"   }--  "**attribution_forms**"

"**attributions**"   }--  "**cultivars**"

"**attributions**"   }--  "**lots**"

"**attributions**"   }--  "**plant_groups**"

"**attributions**"   }--  "**plants**"

"**crossings**"   }--  "**cultivars**"

"**crossings**"   }--  "**cultivars**"

"**cultivars**"   }--  "**lots**"

"**lots**"   }--  "**crossings**"

"**lots**"   }--  "**orchards**"

"**mother_plants**"   }--  "**crossings**"

"**mother_plants**"   }--  "**plants**"

"**mother_plants**"   }--  "**pollen**"

"**plant_groups**"   }--  "**cultivars**"

"**plant_rows**"   }--  "**orchards**"

"**plants**"   }--  "**graftings**"

"**plants**"   }--  "**plant_groups**"

"**plants**"   }--  "**plant_rows**"

"**plants**"   }--  "**rootstocks**"

"**pollen**"   }--  "**cultivars**"

"**queries**"   }--  "**query_groups**"
@enduml
