name: Backend Test

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-test.yml'
      - '.github/actions/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-test.yml'
      - '.github/actions/**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Create .env files
        uses: ./.github/actions/create-env-files

      - name: Install Hasura-CLI
        uses: ./.github/actions/install-hasura-cli

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies for backend/tests
        run: bun install --cwd=backend/tests

      - name: Run backend tests
        run: ./backend/tests/run.sh
