name: Backend Test

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-test.yml'
  pull_request:
    branches:
      - main
      - v3

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "HASURA_GRAPHQL_ADMIN_SECRET=$(openssl rand -hex 16)" >> backend/.env
          echo "HASURA_GRAPHQL_AUTH_HOOK=http://host.docker.internal:8090/authenticate-hasura-request" >> backend/.env
          echo "ACTIONS_URL=http://host.docker.internal:8090/actions" >> backend/.env
          echo "ACTIONS_SECRET=$(openssl rand -hex 16)" >> backend/.env
          echo "HASURA_GRAPHQL_URL=http://localhost:8080/v1/graphql" >> backend/.env

      - name: Install Hasura-CLI
        run: curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies for tests
        run: bun install --cwd=backend/tests

      - name: Install dependencies for cloud-function
        run: bun install --cwd=cloud-function

      - name: Run backend tests
        run: ./backend/tests/run.sh
