name: Generate Database UML

on:
  push:
    paths:
      - 'backend/migrations/**'
      - '.github/workflows/database-uml.yml'
      - '.github/actions/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/migrations/**'
      - '.github/workflows/database-uml.yml'
      - '.github/actions/**'

jobs:
  generate-uml:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "HASURA_GRAPHQL_ADMIN_SECRET=$(openssl rand -hex 16)" >> backend/.env

      - name: Install Hasura-CLI
        uses: ./.github/actions/install-hasura-cli

      - name: Start backend
        uses: ./.github/actions/start-backend

      - name: Generate UML
        run: ./backend/docs/generate-uml.sh

      - name: Check for changes in UML files
        run: |
          if [[ -n $(git diff --name-only backend/docs/database.puml backend/docs/database-light.svg backend/docs/database-dark.svg) ]];
          then
          echo "HAS_CHANGES=true" >> "$GITHUB_ENV"
          else
          echo "HAS_CHANGES=" >> "$GITHUB_ENV"
          fi

      - name: Get branch name
        uses: ./.github/actions/branch-name

      - name: Create Pull Request
        if: ${{ env.HAS_CHANGES }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}-DB-UML
          base: ${{ env.BRANCH_NAME }}
          title: 'Update database UML'
          body: |
            Updates the database UML files.

            PR was automatically created by the database-uml workflow.
          commit-message: 'Update database UML'
          reviewers: ${{ github.actor }}
          delete-branch: true
