name: Frontend Test

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-test.yml'
      - '.github/actions/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-test.yml'
      - '.github/actions/**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup frontend
        uses: ./.github/actions/setup-frontend

      - name: Run frontend tests
        run: yarn --cwd=frontend run test:unit:ci
