name: Frontend Check (tsc, lint, build)

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-check.yml'
  pull_request:
    branches:
      - main
      - v3

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Switch to /frontend
        run: cd frontend

      - name: Create .env file
        run: cp .env.example .env

      - name: Install dependencies
        run: yarn install

      - name: Run tsc
        run: yarn tsc --skipLibCheck

      - name: Run lint
        run: yarn lint

      - name: Run build
        run: yarn build
